# hmmmm. 02/21/2026
library(data.table)
library(lubridate)
library(lattice)
# This code is continually under construction. Looks like 'day_time' field give the best accurate readings for totals.
# Parses and displays charts from Samsung health download generated by Samsung Watch (D513) and Galaxy Wearable app for phone(S23U)

setwd("F:/Samsung/02.15.2026")
daily_summary <- 
fread("com.samsung.shealth.activity.day_summary.20260215102959.csv",skip=1,fill=TRUE)[
	order(create_time)]

#Time difference of -2433 days
ymd("2019-06-19") - ymd("2026-02-15")
	
# Some notes on total days, duplicated create_times, blah...
daily_summary[(update_time - create_time) != 0,.(create_date=as.Date(create_time))][!duplicated(create_date),.(last(.SD) - first(.SD))]
daily_summary[(update_time - create_time) != 0,.(create_date=as.Date(create_time))][,.(last(.SD) - first(.SD))]
daily_summary[(update_time - create_time) != 0,.N,.(create_time,create_date=as.Date(create_time))]
daily_summary[(update_time - create_time) != 0,.(create_time),.(create_date=as.Date(create_time))][,.N,.(create_date)][N == 2,]

daily_summary[day_time != 0,.(create_date=as.Date(create_time))][!duplicated(create_date),.(last(.SD) - first(.SD))]
daily_summary[day_time != 0,.(create_date=as.Date(create_time))][,.(last(.SD) - first(.SD))]
daily_summary[day_time != 0,.N,.(create_time,create_date=as.Date(create_time))]
daily_summary[day_time != 0,.(create_time),.(create_date=as.Date(create_time))][,.N,.(create_date)][N == 2,


# includes milliseconds to minutes and hours, meters to miles conversions 
daily_summary_limited <-
	daily_summary[,
	.(create_time,
	day_time,
	update_time,
	step_count,
	calorie,
	distance.meters=distance,
	miles=(distance * 0.000621371),
	exercise_time,	
	exercise_minutes=((exercise_time/1000)/60),
	exercise_hours=(exercise_time/1000)/(60*60),
	active_time,
	active_minutes=((active_time/1000)/60),
	active_hours=(active_time/1000)/(60* 60))]

daily_summary_limited[!step_count == 0,.N]
daily_summary_limited[step_count == 0,.N]	
# update_time
	dev.new()
	daily_summary_limited[,plot(active_hours ~ update_time,pch=19,col="blue",main="active_hours ~ update_time")]
	daily_summary_limited[,lines(lowess(active_hours ~ update_time),col="red",lwd=3)]
	
	dev.new()
	daily_summary_limited[,plot(miles ~ update_time,pch=19,col="blue",main="miles ~ update_time")]
	daily_summary_limited[,lines(lowess(miles ~ update_time),col="red",lwd=3)]

	dev.new()
	daily_summary_limited[,plot(calorie ~ update_time,pch=19,col="blue",main="calorie ~ update_time")]
	daily_summary_limited[,lines(lowess(calorie ~ update_time),col="red",lwd=3)]
# create_time	
	dev.new()
	daily_summary_limited[,plot(active_hours ~ create_time,pch=19,col="blue",main="active_hours ~ create_time")]
	daily_summary_limited[,lines(lowess(active_hours ~ create_time),col="red",lwd=3)]
	
	dev.new()
	daily_summary_limited[,plot(miles ~ create_time,pch=19,col="blue",main="miles ~ create_time")]
	daily_summary_limited[,lines(lowess(miles ~ create_time),col="red",lwd=3)]

	dev.new()
	daily_summary_limited[,plot(calorie ~ create_time,pch=19,col="blue",main="calorie ~ create_time")]
	daily_summary_limited[,lines(lowess(calorie ~ create_time),col="red",lwd=3)]

# day_time	
	dev.new()
	daily_summary_limited[,plot(active_hours ~ day_time,pch=19,col="blue",main="active_hours ~ day_time")]
	daily_summary_limited[,lines(lowess(active_hours ~ day_time),col="red",lwd=3)]
	
	dev.new()
	daily_summary_limited[,plot(miles ~ day_time,pch=19,col="blue",main="miles ~ day_time")]
	daily_summary_limited[,lines(lowess(miles ~ day_time),col="red",lwd=3)]

	dev.new()
	daily_summary_limited[,plot(calorie ~ day_time,pch=19,col="blue",main="calorie ~ day_time")]
	daily_summary_limited[,lines(lowess(calorie ~ day_time),col="red",lwd=3)]

daily_summary[,IDate.create:=as.IDate(create_time)]
daily_summary[,IDate.update:=as.IDate(update_time)]
daily_summary[,IDate.daytime:=as.IDate(day_time)]

# 11:48 AM 2/20/2026 :: Tricky,tricky,tricky
# There are duplicate time stamps in IDate.create, IDate.update. 
# IDate.daytime  has most accurate sums.
dev.new()
daily_summary[step_count > 0,.(step_count,distance),.(IDate.create)][duplicated(IDate.create)]
daily_summary[step_count > 0,.(step_count=sum(step_count,na.rm=TRUE)),.(year(ymd_hms(create_time)),months(ymd_hms(create_time)))]
daily_summary[step_count > 0,.(step_count=sum(step_count,na.rm=TRUE)),.(year(ymd_hms(create_time)),months(ymd_hms(create_time)))][
,plot(step_count,type="b",cex=2,col=c("red","blue"),main="step_count sum ~ create_time")]


# There are duplicate time stamps:
dev.new()
daily_summary[step_count > 0,.(step_count,distance),.(IDate.update)][duplicated(IDate.update)]
daily_summary[step_count > 0,.(step_count=sum(step_count,na.rm=TRUE)),.(year(ymd_hms(update_time)),months(ymd_hms(update_time)))]
daily_summary[step_count > 0,.(step_count=sum(step_count,na.rm=TRUE)),.(year(ymd_hms(update_time)),months(ymd_hms(update_time)))][
,plot(step_count,type="b",cex=2,col=c("red","blue"),main="step_count sum ~ update_time")]

# There are less duplicate time stamps and more accurate monthly readings
dev.new()
daily_summary[step_count > 0,.(step_count,distance),.(IDate.daytime)][duplicated(IDate.daytime)]
daily_summary[step_count > 0,.(step_count=sum(step_count,na.rm=TRUE)),.(year(ymd(day_time)),months(ymd(day_time)))]
daily_summary[step_count > 0,.(step_count=sum(step_count,na.rm=TRUE)),.(year(ymd(day_time)),months(ymd(day_time)))][
,plot(step_count,type="b",cex=2,col=c("red","blue"),main="step_count sum ~ day_time")]


# with create_time ... data loss

merge(
daily_summary[step_count != 0,.(step_count=sum(step_count,na.rm=TRUE)),.(year(ymd_hms(create_time)))],
daily_summary[distance != 0,.(miles=sum(distance,na.rm=TRUE) * 0.000621371),.(year(ymd_hms(create_time)))],
by="year")[,.SD[,.(steps.per.miles=step_count/miles)],.(year,step_count,miles)][]


merge(
daily_summary[step_count != 0,.(step_count=sum(step_count,na.rm=TRUE)),.(month(ymd_hms(create_time)))],
daily_summary[distance != 0,.(miles=sum(distance,na.rm=TRUE) * 0.000621371),.(month(ymd_hms(create_time)))],
by="month")[,.SD[,.(steps.per.miles=step_count/miles)],.(month,step_count,miles)][]


# with day_time ... less data loss

merge(
daily_summary[step_count != 0,.(step_count=sum(step_count,na.rm=TRUE)),.(year(ymd(day_time)))],
daily_summary[distance != 0,.(miles=sum(distance,na.rm=TRUE) * 0.000621371),.(year(ymd(day_time)))],
by="year")[,.SD[,.(steps.per.miles=step_count/miles)],.(year,step_count,miles)][]

merge(
daily_summary[step_count != 0,.(step_count=sum(step_count,na.rm=TRUE)),.(month(ymd(day_time)))],
daily_summary[distance != 0,.(miles=sum(distance,na.rm=TRUE) * 0.000621371),.(month(ymd(day_time)))],
by="month")[,.SD[,.(steps.per.miles=step_count/miles)],.(month,step_count,miles)][]


# with IDate.create_time ... data loss
merge(
daily_summary[step_count !=0,.(step_count=sum(step_count,na.rm=TRUE)),.(IDate.create)],
daily_summary[distance !=0,.(miles=sum(distance,na.rm=TRUE) * 0.000621371),.(IDate.create)],
by="IDate.create")[,.SD[,.(steps.per.miles=step_count/miles)],.(year(IDate.create),step_count,miles)][]

merge(
daily_summary[,.(step_count=sum(step_count,na.rm=TRUE)),.(IDate.create)],
daily_summary[,.(miles=sum(distance,na.rm=TRUE) * 0.000621371),.(IDate.create)],
by="IDate.create")


# with IDate.daytime ... less data loss
merge(
daily_summary[step_count !=0,.(step_count=sum(step_count,na.rm=TRUE)),.(IDate.daytime)],
daily_summary[distance !=0,.(miles=sum(distance,na.rm=TRUE) * 0.000621371),.(IDate.daytime)],
by="IDate.daytime")[,.SD[,.(steps.per.miles=step_count/miles)],.(year(IDate.daytime),step_count,miles)][]

merge(
daily_summary[,.(step_count=sum(step_count,na.rm=TRUE)),.(IDate.daytime)],
daily_summary[,.(miles=sum(distance,na.rm=TRUE) * 0.000621371),.(IDate.daytime)],
by="IDate.daytime")


# with create_time ... data loss
# steps bar chart
t1 <- daily_summary_limited[step_count > 0,.(step_count=sum(step_count,na.rm=TRUE)),.(year=year(ymd_hms(create_time)),months=months(ymd_hms(create_time)))]
t1[,index:=.I]
dev.new();t1[,plot(step_count,type="b",xlab="Months 6/2019 - 2/15/2026",cex=2,col=c("red","blue"))];grid(col="red")
list <- as.list(t1[,paste0(substr(months,1,3),substr(year,3,4))])
dev.new();t1[,barplot(step_count,names=list, col = c("lightblue", "mistyrose",
                "lightcyan", "lavender"),xlab="Months 6/2019 - 2/15/2026",ylab="Steps",cex.names=.75,main="Samsung Step Count")]
				grid(col="red")
				
# miles bar chart				
t2 <- daily_summary_limited[miles > 0,.(miles=sum(miles,na.rm=TRUE)),.(year=year(ymd_hms(create_time)),months=months(ymd_hms(create_time)))]
t2[,index:=.I]
dev.new();t2[,plot(miles,type="b",xlab="Months 6/2019 - 2/15/2026",cex=2,col=c("red","blue"))];grid(col="red")
list <- as.list(t2[,paste0(substr(months,1,3),substr(year,3,4))])
dev.new();t2[,barplot(miles,names=list, col = c("lightblue", "mistyrose",
                "lightcyan", "lavender"),xlab="Months 6/2019 - 2/15/2026",ylab="Miles",cex.names=.75,main="Samsung Miles Count")]
				grid(col="red")

# with day_time ... less data loss
# steps bar chart
t1 <- daily_summary_limited[step_count > 0,.(step_count=sum(step_count,na.rm=TRUE)),.(year=year(ymd(day_time)),months=months(ymd(day_time)))]
t1[,index:=.I]
dev.new();t1[,plot(step_count,type="b",xlab="Months 6/2019 - 2/15/2026",cex=2,col=c("red","blue"))];grid(col="red")
list <- as.list(t1[,paste0(substr(months,1,3),substr(year,3,4))])
dev.new();t1[,barplot(step_count,names=list, col = c("lightblue", "mistyrose",
                "lightcyan", "lavender"),xlab="Months 6/2019 - 2/15/2026",ylab="Steps",cex.names=.75,main="Samsung Step Count")]
				grid(col="red")
				
# miles bar chart				
t2 <- daily_summary_limited[miles > 0,.(miles=sum(miles,na.rm=TRUE)),.(year=year(ymd(day_time)),months=months(ymd(day_time)))]
t2[,index:=.I]
dev.new();t2[,plot(miles,type="b",xlab="Months 6/2019 - 2/15/2026",cex=2,col=c("red","blue"))];grid(col="red")
list <- as.list(t2[,paste0(substr(months,1,3),substr(year,3,4))])
dev.new();t2[,barplot(miles,names=list, col = c("lightblue", "mistyrose",
                "lightcyan", "lavender"),xlab="Months 6/2019 - 2/15/2026",ylab="Miles",cex.names=.75,main="Samsung Miles Count")]
				grid(col="red")

# merge steps and miles
t3 <- merge(t1,t2,all=TRUE,by=c("index","year","months"))
t3[,steps.per.mile:=step_count/miles]
t3

# step and mile sums from June 20 2019 to 2/15/2026
# Two months covering December 2022 and January 2023 had (short) step data generated solely by phone and not (the most accurate) phone/watch combination.

#  t3[2:81][c(-43,-44)] for more accurrate averages
t3[10:81][,.(Pan_miles=sum(miles),Pan_steps=sum(step_count))]
 
t1[,sum(step_count)]
# 
t2[,sum(miles)]
# 
# For comparison: Distance around WGS84 ellipsoid (e.g. Earth) at 49th paralell would equal 17,638 miles.
# Such an exact circumnavigation would also have to include some pretty stiff Pacific and Atlantic ocean paddles...


t3[, .(mean_miles_per_month=mean(miles),
	mean.steps_per_month=mean(step_count),
	mean_steps.per.mile=mean(steps.per.mile),
	mean.steps.per.foot=sum(step_count)/((sum(miles) * 5280)),
	mean.feet.per.step=sum(miles) * (5280/sum(step_count)))]
	
# mean_miles_per_month mean.steps_per_month mean_steps.per.mile mean.steps.per.foot mean.feet.per.step

# steps per mile
dev.new();t3[,plot(steps.per.mile,type="b",xlab="Months 6/2019 - 2/15/2026",cex=2,col=c("red","blue"))];grid(col="red")
list <- as.list(t3[,paste0(substr(months,1,3),substr(year,3,4))])
dev.new();t3[,barplot(steps.per.mile,names=list, col = c("lightblue", "mistyrose",
                "lightcyan", "lavender"),xlab="Months 6/2019 - 2/15/2026",ylab="Steps per Mile",cex.names=.75,main="Samsung Steps per Mile")]
				grid(col="red")

# End

daily_summary[active_time > 0,.(
	year=year(day_time),
	active_time,
	exercise_time,
	run_time,
	walk_time,
	others_time)]

daily_summary[,year:=year(ymd_hms(create_time))]
daily_summary[active_time > 0,
	
	.(active_hours=sum((active_time/1000)/(60*60),na.rm=TRUE),
	run_hours=sum((run_time/1000)/(60*60),na.rm=TRUE),
	exercise_hours=sum((exercise_time/1000)/(60*60),na.rm=TRUE),
	walk_hours=sum((walk_time/1000)/(60*60),na.rm=TRUE),
	other_hours=sum((others_time/1000)/(60*60),na.rm=TRUE)),
	.(year)]


daily_summary[,year:=year(ymd_hms(create_time))]
daily_summary[,month:=month(ymd_hms(create_time))]


hours_years <- 
daily_summary[active_time > 0,
	
	.(active_hours=sum((active_time/1000)/(60*60),na.rm=TRUE),
	run_hours=sum((run_time/1000)/(60*60),na.rm=TRUE),
	exercise_hours=sum((exercise_time/1000)/(60*60),na.rm=TRUE),
	walk_hours=sum((walk_time/1000)/(60*60),na.rm=TRUE),
	other_hours=sum((others_time/1000)/(60*60),na.rm=TRUE)),
	.(year)]
plot.new()
hours_years[,barchart(~other_hours+exercise_hours+walk_hours+active_hours | 
	as.factor(year),origin = 0,col=rainbow(4),
	auto.key=list(col=rainbow(4),rectangles=FALSE,reverse.rows=TRUE))]

hours_months <- 
daily_summary[active_time > 0,
	
	.(active_hours=sum((active_time/1000)/(60*60),na.rm=TRUE),
	run_hours=sum((run_time/1000)/(60*60),na.rm=TRUE),
	exercise_hours=sum((exercise_time/1000)/(60*60),na.rm=TRUE),
	walk_hours=sum((walk_time/1000)/(60*60),na.rm=TRUE),
	other_hours=sum((others_time/1000)/(60*60),na.rm=TRUE)),
	.(month)]

plot.new()
hours_months[,barchart(~other_hours+exercise_hours+walk_hours+active_hours | 
	as.factor(month),origin = 0,col=rainbow(4),
	auto.key=list(col=rainbow(4),rectangles=FALSE,reverse.rows=TRUE))]

# statistics
dc <- daily_summary[step_count > 0 | distance > 0,
	.(step_count,miles=round(distance * 0.000621371,2)),.(IDate.create)]
	dc[,.(
	mean.sc=mean(step_count),
	mean.mi=mean(miles),
	sd.sc=sd(step_count,na.rm=TRUE),
	sd.mi=sd(miles,na.rm=TRUE),
	mad.sc=mad(step_count),
	mad.mi=mad(miles),
	var.sc=var(step_count),
	var.mi=var(miles))]

dc <- daily_summary[step_count > 0 | distance > 0,
	.(step_count,miles=round(distance * 0.000621371,2)),.(IDate.daytime)]
	dc[,.(
	mean.sc=mean(step_count),
	mean.mi=mean(miles),
	sd.sc=sd(step_count,na.rm=TRUE),
	sd.mi=sd(miles,na.rm=TRUE),
	mad.sc=mad(step_count),
	mad.mi=mad(miles),
	var.sc=var(step_count),
	var.mi=var(miles))]


dc <- daily_summary[step_count > 0 | distance > 0,
	.(step_count=as.integer(step_count),miles=round(distance * 0.000621371,2)),.(year(IDate.create))]
	dc[,.(
	sum.sc=sum(step_count),
	sum.mi=sum(miles),
	mean.sc=mean(step_count),
	mean.mi=mean(miles),
	median.sc=median(step_count),
	median.mi=median(miles),
	sd.sc=sd(step_count,na.rm=TRUE),
	sd.mi=sd(miles,na.rm=TRUE)),.(year)]

# Add IDate (rdata.table) fields																									
daily_summary[,IDate.create:=as.IDate(create_time)]
daily_summary[,IDate.update:=as.IDate(update_time)]
daily_summary[,IDate.daytime:=as.IDate(day_time)]

step.miles.merge <-
merge(
daily_summary[step_count > 0,.(step_count=sum(step_count,na.rm=TRUE)),.(IDate.create,IDate.daytime,month(day_time),year(day_time))],
daily_summary[distance > 0,.(miles=sum(distance,na.rm=TRUE) * 0.000621371),
.(IDate.daytime,month(day_time),year(day_time))],by=c("IDate.daytime","month","year"))[,
.SD[,.(steps.per.miles=step_count/miles)],.(year,month,IDate.create,IDate.daytime,step_count,miles)][order(year,month,IDate.daytime)]

# under 6000 steps per day
dev.new()
step.miles.merge[step_count < 6000,
	.(step_count,IDate.daytime)][,
	plot(step_count ~ IDate.daytime,type="p",cex=1,pch=19,col="red",main="Step Count Under 6000")]

# under 8500 steps per day
dev.new()
step.miles.merge[step_count < 8500,
	.(step_count,IDate.daytime)][,
	plot(step_count ~ IDate.daytime,type="p",cex=1,pch=19,col="blue",main="Step Count Under 8000")]
	
# under 10000 steps per day
dev.new()
step.miles.merge[step_count < 10000,
	.(step_count,IDate.daytime)][,
	plot(step_count ~ IDate.daytime,type="p",cex=1,pch=19,col="black",main="Step Count Under 10000")]	

# The 'BIG' Chart
# start new
dev.new()
plot.new()
step.miles.merge[,plot(miles~ IDate.daytime,type="l",col="blue",ylab="Miles and Steps",xlab="Year")];
title(main="Miles(blue) range(0:20) and Steps/10000(red) range(0:50K) with 'lowess' approximations",line=2,cex.main=2)
title(main="Black Diamonds < 8500 steps. Black line = 10,000 steps",line=-2,cex.main=2)
step.miles.merge[,lines(step_count/10000 ~ IDate.daytime,col="red",lwd=3)];
step.miles.merge[,lines(lowess(miles ~ IDate.daytime),col="blue",lwd=3)];
step.miles.merge[,lines(lowess(step_count/10000 ~ IDate.daytime),col="red",lwd=3)];
step.miles.merge[step_count < 8500,
	# & (month(IDate.daytime) > 1 &	month(IDate.daytime) != 12),
	.(step_count,IDate.daytime)][,
	points(step_count/10000 ~ IDate.daytime,,cex=1.5,pch=18,col="black")]
abline(h=1,lwd=3,col="black")
grid(20,lwd=1,col = "lightgray")
# end new

Under8500 <- step.miles.merge[step_count < 8500, 
	# & (month(IDate.daytime) > 2 & month(IDate.daytime) != 12),
	.(step_count,IDate.daytime)]

Under8500 <- step.miles.merge[step_count < 8500,]

dev.new()
plot.new()
Under8500[,plot(step_count ~ IDate.create,type="p",cex=3,pch=18,col="black")];
Under8500[,lines(lowess(step_count~ IDate.daytime),col="red",lwd=3)]
dev.new()
plot.new()
Under8500[,plot(miles ~ IDate.create,type="p",cex=3,pch=18,col="black")];
Under8500[,lines(lowess(miles~ IDate.daytime),col="red",lwd=3)]
dev.new()
plot.new()
Under8500[miles < 3.5,plot(miles ~ IDate.create,type="p",cex=3,pch=18,col="black")][-c(35:47)]
Under8500[miles < 3.5,lines(lowess(miles~ IDate.daytime),col="red",lwd=3)]

daily_summary_limited[step_count > 0,.(step_count,year=year(ymd_hms(create_time)))]
daily_summary_limited[step_count > 0,.(step_count,year=year(ymd_hms(update_time)))]
daily_summary_limited[step_count > 0,.(step_count,year=year(ymd(day_time)))]

daily_summary_limited[miles > 0,.(step_count,year=year(ymd_hms(create_time)))]
daily_summary_limited[miles > 0,.(step_count,year=year(ymd_hms(update_time)))]
daily_summary_limited[miles > 0,.(step_count,year=year(ymd(day_time)))]


ymd("2019-06-19") - ymd("2026-02-15")
#Time difference of -2433 days

daily_summary_limited[miles > 0,.(miles=sum(miles,na.rm=TRUE),step_count=sum(step_count,na.rm=TRUE)),
.(day(update_time),month(update_time),year(update_time))]

daily_summary_limited[miles > 0,.(miles=sum(miles,na.rm=TRUE),step_count=sum(step_count,na.rm=TRUE)),
.(day(create_time),month(create_time),year(create_time))]

daily_summary_limited[miles > 0,.(miles=sum(miles,na.rm=TRUE),step_count=sum(step_count,na.rm=TRUE)),
.(day(day_time),month(day_time),year(day_time))]

dev.new()
daily_summary_limited[step_count > 0,.(miles=sum(miles,na.rm=TRUE),step_count=sum(step_count,na.rm=TRUE)),
.(day(day_time),month(day_time),year(day_time))][
,barchart( day ~ step_count/1000  | as.factor(month) + as.factor(year),
horizontal=TRUE,origin=0,allow.multiple=TRUE,col=rainbow(30))]

dev.new()
daily_summary_limited[miles > 0,.(miles=sum(miles,na.rm=TRUE),step_count=sum(step_count,na.rm=TRUE)),
.(day(day_time),month(day_time),year(day_time))][
,barchart( day ~ as.integer(miles)  | as.factor(month) + as.factor(year),
horizontal=TRUE,origin=0,allow.multiple=TRUE,col=rainbow(30))]
