library(data.table)
library(lubridate)
library(lattice)
# This code is continually under construction.
# Parses and displays charts from Samsung health download generated by Samsung 4 Watch and Galaxy Wearable app for phone (S23U)

setwd("F:/Samsung/08.21.2025")
daily_summary <- 
fread("com.samsung.shealth.activity.day_summary.20250821175042.csv",skip=1,fill=TRUE)[
	order(create_time)]
	
# Some notes on total days, duplicated create_times, blah...
daily_summary[(update_time - create_time) != 0,.(create_date=as.Date(create_time))][!duplicated(create_date),.(last(.SD) - first(.SD))]
daily_summary[(update_time - create_time) != 0,.(create_date=as.Date(create_time))][,.(last(.SD) - first(.SD))]
daily_summary[(update_time - create_time) != 0,.N,.(create_time,create_date=as.Date(create_time))]
daily_summary[(update_time - create_time) != 0,.(create_time),.(create_date=as.Date(create_time))][,.N,.(create_date)][N == 2,]

# includes milliseconds to minutes and hours, meters to miles conversions 
daily_summary_limited <-
	daily_summary[,
	.(create_time,
	update_time,
	step_count,
	calorie,
	distance.meters=distance,
	miles=(distance * 0.000621371),
	exercise_time,	
	exercise_minutes=((exercise_time/1000)/60),
	exercise_hours=(exercise_time/1000)/(60*60),
	active_time,
	active_minutes=((active_time/1000)/60),
	active_hours=(active_time/1000)/(60* 60))]

daily_summary_limited[!step_count == 0,.N]
daily_summary_limited[step_count == 0,.N]	

	dev.new()
	daily_summary_limited[,plot(active_hours ~ update_time,pch=19,col="blue",main="active_hours ~ update_time")]
	daily_summary_limited[,lines(lowess(active_hours ~ update_time),col="red",lwd=3)]
	
	dev.new()
	daily_summary_limited[,plot(miles ~ update_time,pch=19,col="blue",main="miles ~ update_time")]
	daily_summary_limited[,lines(lowess(miles ~ update_time),col="red",lwd=3)]

	dev.new()
	daily_summary_limited[,plot(active_hours ~ create_time,pch=19,col="blue",main="active_hours ~ create_time")]
	daily_summary_limited[,lines(lowess(active_hours ~ create_time),col="red",lwd=3)]
	
	dev.new()
	daily_summary_limited[,plot(miles ~ create_time,pch=19,col="blue",main="miles ~ create_time")]
	daily_summary_limited[,lines(lowess(miles ~ create_time),col="red",lwd=3)]

	dev.new()
	daily_summary_limited[,plot(calorie ~ create_time,pch=19,col="blue",main="calorie ~ create_time")]
	daily_summary_limited[,lines(lowess(calorie ~ create_time),col="red",lwd=3)]

daily_summary[,IDate.create:=as.IDate(create_time)]
daily_summary[,IDate.update:=as.IDate(update_time)]

# There are duplicate time stamps:
daily_summary[step_count > 0,.(step_count,distance),.(IDate.create)][duplicated(IDate.create)]
daily_summary[step_count > 0,.(step_count=sum(step_count,na.rm=TRUE)),.(year(ymd_hms(create_time)),months(ymd_hms(create_time)))]
daily_summary[step_count > 0,.(step_count=sum(step_count,na.rm=TRUE)),.(year(ymd_hms(create_time)),months(ymd_hms(create_time)))][,plot(step_count,type="b",cex=2,col=c("red","blue"))]

merge(
daily_summary[step_count != 0,.(step_count=sum(step_count,na.rm=TRUE)),.(year(ymd_hms(create_time)))],
daily_summary[distance != 0,.(miles=sum(distance,na.rm=TRUE) * 0.000621371),.(year(ymd_hms(create_time)))],
by="year")[,.SD[,.(steps.per.miles=step_count/miles)],.(year,step_count,miles)][]


merge(
daily_summary[step_count != 0,.(step_count=sum(step_count,na.rm=TRUE)),.(month(ymd_hms(create_time)))],
daily_summary[distance != 0,.(miles=sum(distance,na.rm=TRUE) * 0.000621371),.(month(ymd_hms(create_time)))],
by="month")[,.SD[,.(steps.per.miles=step_count/miles)],.(month,step_count,miles)][]


merge(
daily_summary[step_count !=0,.(step_count=sum(step_count,na.rm=TRUE)),.(IDate.create)],
daily_summary[distance !=0,.(miles=sum(distance,na.rm=TRUE) * 0.000621371),.(IDate.create)],
by="IDate.create")[,.SD[,.(steps.per.miles=step_count/miles)],.(year(IDate.create),step_count,miles)][]


merge(
daily_summary[,.(step_count=sum(step_count,na.rm=TRUE)),.(IDate.create)],
daily_summary[,.(miles=sum(distance,na.rm=TRUE) * 0.000621371),.(IDate.create)],
by="IDate.create")


# steps bar chart
t1 <- daily_summary_limited[step_count > 0,.(step_count=sum(step_count,na.rm=TRUE)),.(year=year(ymd_hms(create_time)),months=months(ymd_hms(create_time)))]
t1[,index:=.I]
dev.new();t1[,plot(step_count,type="b",xlab="Months 6/2019 - 8/2025",cex=2,col=c("red","blue"))];grid(col="red")
list <- as.list(t1[,paste0(substr(months,1,3),substr(year,3,4))])
dev.new();t1[,barplot(step_count,names=list, col = c("lightblue", "mistyrose",
                "lightcyan", "lavender"),xlab="Months 6/2019 - 8/2025",ylab="Steps",cex.names=.75,main="Samsung Step Count")]
				grid(col="red")
				#
				
# miles bar chart				
t2 <- daily_summary_limited[miles > 0,.(miles=sum(miles,na.rm=TRUE)),.(year=year(ymd_hms(create_time)),months=months(ymd_hms(create_time)))]
t2[,index:=.I]
dev.new();t2[,plot(miles,type="b",xlab="Months 6/2019 - 8/2025",cex=2,col=c("red","blue"))];grid(col="red")
list <- as.list(t2[,paste0(substr(months,1,3),substr(year,3,4))])
dev.new();t2[,barplot(miles,names=list, col = c("lightblue", "mistyrose",
                "lightcyan", "lavender"),xlab="Months 6/2019 - 8/2025",ylab="Miles",cex.names=.75,main="Samsung Miles Count")]
				grid(col="red")
				#

# merge steps and miles
t3 <- merge(t1,t2,all=TRUE,by=c("index","year","months"))
t3[,steps.per.mile:=step_count/miles]
t3

# sums June 20 2019 to August 21 2025
# Two months covering December 2022 and January 2023 had step data generated solely by phone not phone/watch combination. 
t1[,sum(step_count)]
# 36621502
t2[,sum(miles)]
# 15917.39
# For comparison: Distance around WGS84 ellipsoid (e.g. Earth) at 49th paralell
# 17,638 miles


# steps per mile
dev.new();t3[,plot(steps.per.mile,type="b",xlab="Months 6/2019 - 8/2025",cex=2,col=c("red","blue"))];grid(col="red")
list <- as.list(t3[,paste0(substr(months,1,3),substr(year,3,4))])
dev.new();t3[,barplot(steps.per.mile,names=list, col = c("lightblue", "mistyrose",
                "lightcyan", "lavender"),xlab="Months 6/2019 - 8/2025",ylab="Steps per Mile",cex.names=.75,main="Samsung Steps per Mile")]
				grid(col="red")

# End

daily_summary[active_time > 0,.(
	year(create_time),
	active_time,
	exercise_time,
	run_time,
	walk_time,
	others_time)]

daily_summary[,year:=year(ymd_hms(create_time))]
daily_summary[active_time > 0,
	
	.(active_hours=sum((active_time/1000)/(60*60),na.rm=TRUE),
	run_hours=sum((run_time/1000)/(60*60),na.rm=TRUE),
	exercise_hours=sum((exercise_time/1000)/(60*60),na.rm=TRUE),
	walk_hours=sum((walk_time/1000)/(60*60),na.rm=TRUE),
	other_hours=sum((others_time/1000)/(60*60),na.rm=TRUE)),
	.(year)]


daily_summary[,year:=year(ymd_hms(create_time))]
daily_summary[,month:=month(ymd_hms(create_time))]


hours_years <- 
daily_summary[active_time > 0,
	
	.(active_hours=sum((active_time/1000)/(60*60),na.rm=TRUE),
	run_hours=sum((run_time/1000)/(60*60),na.rm=TRUE),
	exercise_hours=sum((exercise_time/1000)/(60*60),na.rm=TRUE),
	walk_hours=sum((walk_time/1000)/(60*60),na.rm=TRUE),
	other_hours=sum((others_time/1000)/(60*60),na.rm=TRUE)),
	.(year)]
plot.new()
hours_years[,barchart(~other_hours+exercise_hours+walk_hours+active_hours | 
	as.factor(year),origin = 0,col=rainbow(4),
	auto.key=list(col=rainbow(4),rectangles=FALSE,reverse.rows=TRUE))]


hours_months <- 
daily_summary[active_time > 0,
	
	.(active_hours=sum((active_time/1000)/(60*60),na.rm=TRUE),
	run_hours=sum((run_time/1000)/(60*60),na.rm=TRUE),
	exercise_hours=sum((exercise_time/1000)/(60*60),na.rm=TRUE),
	walk_hours=sum((walk_time/1000)/(60*60),na.rm=TRUE),
	other_hours=sum((others_time/1000)/(60*60),na.rm=TRUE)),
	.(month)]

plot.new()
hours_months[,barchart(~other_hours+exercise_hours+walk_hours+active_hours | 
	as.factor(month),origin = 0,col=rainbow(4),
	auto.key=list(col=rainbow(4),rectangles=FALSE,reverse.rows=TRUE))]


dc <- daily_summary[step_count > 0 | distance > 0,
	.(step_count,miles=round(distance * 0.000621371,2)),.(IDate.create)]
	dc[,.(
	mean.sc=mean(step_count),
	mean.mi=mean(miles),
	sd.sc=sd(step_count,na.rm=TRUE),
	sd.mi=sd(miles,na.rm=TRUE),
	mad.sc=mad(step_count),
	mad.mi=mad(miles),
	var.sc=var(step_count),
	var.mi=var(miles))]


dc <- daily_summary[step_count > 0 | distance > 0,
	.(step_count=as.integer(step_count),miles=round(distance * 0.000621371,2)),.(year(IDate.create))]
	dc[,.(
	sum.sc=sum(step_count),
	sum.mi=sum(miles),
	mean.sc=mean(step_count),
	mean.mi=mean(miles),
	median.sc=median(step_count),
	median.mi=median(miles),
	sd.sc=sd(step_count,na.rm=TRUE),
	sd.mi=sd(miles,na.rm=TRUE)),.(year)]


daily_summary[,IDate.create:=as.IDate(create_time)]
daily_summary[,IDate.update:=as.IDate(update_time)]

step.miles.merge <-
merge(
daily_summary[step_count > 0,.(step_count=sum(step_count,na.rm=TRUE)),.(IDate.create,month(create_time),year(create_time))],
daily_summary[distance > 0,.(miles=sum(distance,na.rm=TRUE) * 0.000621371),
.(IDate.create,month(create_time),year(create_time))],by=c("IDate.create","month","year"))[,
.SD[,.(steps.per.miles=step_count/miles)],.(year,month,IDate.create,step_count,miles)][order(year,month,IDate.create)]


# under 6000 steps per day
dev.new()
step.miles.merge[step_count < 6000,
	.(step_count,IDate.create)][,
	plot(step_count ~ IDate.create,type="p",cex=1,pch=19,col="red",main="Step Count Under 6000")]

# under 8500 steps per day
dev.new()
step.miles.merge[step_count < 8500,
	.(step_count,IDate.create)][,
	plot(step_count ~ IDate.create,type="p",cex=1,pch=19,col="blue",main="Step Count Under 8000")]
	
# under 10000 steps per day
dev.new()
step.miles.merge[step_count < 10000,
	.(step_count,IDate.create)][,
	plot(step_count ~ IDate.create,type="p",cex=1,pch=19,col="black",main="Step Count Under 10000")]	


# start new
step.miles.merge[,plot(miles~ IDate.create,type="l",col="blue",ylab="Miles and Steps",xlab="Year")];
title(main="Miles(blue) range(0:20) and Steps/10000(red) range(0:50K) with 'lowess' approximations",line=2,cex.main=2)
title(main="Black Diamonds < 8500 steps. Black line = 10,000 steps",line=-2,cex.main=2)

step.miles.merge[,lines(step_count/10000 ~ IDate.create,col="red",lwd=3)];
step.miles.merge[,lines(lowess(miles ~ IDate.create),col="blue",lwd=3)];
step.miles.merge[,lines(lowess(step_count/10000 ~ IDate.create),col="red",lwd=3)];
step.miles.merge[step_count < 8500,
	# & (month(IDate.create) > 1 &	month(IDate.create) != 12),
	.(step_count,IDate.create)][,
	points(step_count/10000 ~ IDate.create,,cex=1.5,pch=18,col="black")]
abline(h=1,lwd=3,col="black")
grid(20,lwd=1,col = "lightgray")
# end new


Under8500 <- step.miles.merge[step_count < 8500, 
	# & (month(IDate.create) > 2 & month(IDate.create) != 12),
	.(step_count,IDate.create)]

Under8500 <- step.miles.merge[step_count < 8500,]

Under8500[,plot(step_count ~ IDate.create,type="p",cex=3,pch=18,col="black")];
Under8500[,lines(lowess(step_count~ IDate.create),col="red",lwd=3)]

Under8500[,plot(miles ~ IDate.create,type="p",cex=3,pch=18,col="black")];
Under8500[,lines(lowess(miles~ IDate.create),col="red",lwd=3)]

Under8500[miles < 3.5,plot(miles ~ IDate.create,type="p",cex=3,pch=18,col="black")][-c(35:47)]
Under8500[miles < 3.5,lines(lowess(miles~ IDate.create),col="red",lwd=3)]




daily_summary_limited[step_count > 0,.(step_count,year=year(ymd_hms(create_time)))]
daily_summary_limited[step_count > 0,.(step_count,year=year(ymd_hms(update_time)))]

daily_summary_limited[miles > 0,.(step_count,year=year(ymd_hms(create_time)))]
daily_summary_limited[miles > 0,.(step_count,year=year(ymd_hms(update_time)))]


daily_summary_limited[step_count > 0,.(miles=sum(miles,na.rm=TRUE),step_count=sum(step_count,na.rm=TRUE)),
.(day(update_time),month(update_time),year(update_time))]

daily_summary_limited[step_count > 0,.(miles=sum(miles,na.rm=TRUE),step_count=sum(step_count,na.rm=TRUE)),
.(day(create_time),month(create_time),year(create_time))]


daily_summary_limited[miles > 0,.(miles=sum(miles,na.rm=TRUE),step_count=sum(step_count,na.rm=TRUE)),
.(day(update_time),month(update_time),year(update_time))]

daily_summary_limited[miles > 0,.(miles=sum(miles,na.rm=TRUE),step_count=sum(step_count,na.rm=TRUE)),
.(day(create_time),month(create_time),year(create_time))]


dev.new()
daily_summary_limited[step_count > 0,.(miles=sum(miles,na.rm=TRUE),step_count=sum(step_count,na.rm=TRUE)),
.(day(create_time),month(create_time),year(create_time))][
,barchart( day ~ step_count/1000  | as.factor(month) + as.factor(year),
horizontal=TRUE,origin=0,allow.multiple=TRUE,col=rainbow(30))]

dev.new()
daily_summary_limited[miles > 0,.(miles=sum(miles,na.rm=TRUE),step_count=sum(step_count,na.rm=TRUE)),
.(day(create_time),month(create_time),year(create_time))][
,barchart( day ~ as.integer(miles)  | as.factor(month) + as.factor(year),
horizontal=TRUE,origin=0,allow.multiple=TRUE,col=rainbow(30))]
# End
